package com.example.anonymous.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bw.android.cloudmusic.MusicCloudPackage.MusicCloudBean;
import com.bw.android.cloudmusic.MusicListPakage.MusicListBean;
import com.bw.android.cloudmusic.PlayMusicPackage.PlayMusicBean;

import com.example.anonymous.greendao.MusicCloudBeanDao;
import com.example.anonymous.greendao.MusicListBeanDao;
import com.example.anonymous.greendao.PlayMusicBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig musicCloudBeanDaoConfig;
    private final DaoConfig musicListBeanDaoConfig;
    private final DaoConfig playMusicBeanDaoConfig;

    private final MusicCloudBeanDao musicCloudBeanDao;
    private final MusicListBeanDao musicListBeanDao;
    private final PlayMusicBeanDao playMusicBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        musicCloudBeanDaoConfig = daoConfigMap.get(MusicCloudBeanDao.class).clone();
        musicCloudBeanDaoConfig.initIdentityScope(type);

        musicListBeanDaoConfig = daoConfigMap.get(MusicListBeanDao.class).clone();
        musicListBeanDaoConfig.initIdentityScope(type);

        playMusicBeanDaoConfig = daoConfigMap.get(PlayMusicBeanDao.class).clone();
        playMusicBeanDaoConfig.initIdentityScope(type);

        musicCloudBeanDao = new MusicCloudBeanDao(musicCloudBeanDaoConfig, this);
        musicListBeanDao = new MusicListBeanDao(musicListBeanDaoConfig, this);
        playMusicBeanDao = new PlayMusicBeanDao(playMusicBeanDaoConfig, this);

        registerDao(MusicCloudBean.class, musicCloudBeanDao);
        registerDao(MusicListBean.class, musicListBeanDao);
        registerDao(PlayMusicBean.class, playMusicBeanDao);
    }
    
    public void clear() {
        musicCloudBeanDaoConfig.getIdentityScope().clear();
        musicListBeanDaoConfig.getIdentityScope().clear();
        playMusicBeanDaoConfig.getIdentityScope().clear();
    }

    public MusicCloudBeanDao getMusicCloudBeanDao() {
        return musicCloudBeanDao;
    }

    public MusicListBeanDao getMusicListBeanDao() {
        return musicListBeanDao;
    }

    public PlayMusicBeanDao getPlayMusicBeanDao() {
        return playMusicBeanDao;
    }

}
